// Misc. Settings
export const SET_NAVBAR = 'SET_NAVBAR';
// (0) Google OAuth Management
export const SIGN_IN = 'SIGN_IN';
export const SIGN_OUT = 'SIGN_OUT';
export const DEV_SIGN_IN = 'DEV_SIGN_IN';
// (1) User Management
export const FETCH_USER = 'FETCH_USER';
export const FETCH_USERS = 'FETCH_USERS';
export const FETCH_ALL_USERS = 'FETCH_ALL_USERS';
// (2) Tribute Management
export const FETCH_TRIBUTE = 'FETCH_TRIBUTE';
export const FETCH_ALL_TRIBUTES = 'FETCH_ALL_TRIBUTES';
// (3) Donations Management
export const FETCH_DONATION = 'FETCH_DONATION';
export const FETCH_DONATIONS = 'FETCH_DONATIONS';
export const FETCH_ALL_DONATIONS = 'FETCH_ALL_DONATIONS';
export const CLEAR_DONATIONS_QUEUE = 'CLEAR_DONATIONS_QUEUE';
// (4a) Resource List
export const FETCH_RESOURCE_LIST_ITEM = 'FETCH_RESOURCE_LIST_ITEM';
export const FETCH_RESOURCE_LIST_ITEMS = 'FETCH_RESOURCE_LIST_ITEMS';
export const FETCH_ALL_RESOURCE_LIST_ITEMS = 'FETCH_ALL_RESOURCE_LIST_ITEMS';
export const CLEAR_RESOURCE_LIST_QUEUE = 'CLEAR_RESOURCE_LIST_QUEUE';
// (4b) Resource Events
export const FETCH_RESOURCE_EVENT = 'FETCH_RESOURCE_EVENT';
export const FETCH_RESOURCE_EVENTS = 'FETCH_RESOURCE_EVENTS';
export const FETCH_ALL_RESOURCE_EVENTS = 'FETCH_ALL_RESOURCE_EVENTS';
export const CLEAR_RESOURCE_EVENT_QUEUE = 'CLEAR_RESOURCE_EVENT_QUEUE';
// (5) Life Management
export const FETCH_LIFE_EVENT = 'FETCH_LIFE_EVENT';
export const FETCH_LIFE_EVENTS = 'FETCH_LIFE_EVENTS';
export const FETCH_ALL_LIFE_EVENTS = 'FETCH_ALL_LIFE_EVENTS';
export const CLEAR_LIFE_EVENTS_QUEUE = 'CLEAR_LIFE_EVENTS_QUEUE';
// (6) Item Management
export const FETCH_ITEM = 'FETCH_ITEM';
export const FETCH_ITEMS = 'FETCH_ITEMS';
export const FETCH_ALL_ITEMS = 'FETCH_ALL_ITEMS';
// (7) Item Management
export const FETCH_ALL_MENTORS = 'FETCH_ALL_MENTORS';
export const FETCH_PURCHASE = 'FETCH_PURCHASE';
export const FETCH_PURCHASES = 'FETCH_PURCHASES';
export const FETCH_ALL_PURCHASES = 'FETCH_ALL_PURCHASES';
export const CLEAR_PURCHASES_QUEUE = 'CLEAR_PURCHASES_QUEUE';
// (8) Game State Management
export const FETCH_GAMESTATE = 'FETCH_GAMESTATE';
// (9) Tribute Stats
export const FETCH_TRIBUTE_STAT = 'FETCH_TRIBUTE_STAT';
export const FETCH_TRIBUTE_STATS = 'FETCH_TRIBUTE_STATS';
export const FETCH_ALL_TRIBUTE_STATS = 'FETCH_ALL_TRIBUTE_STATS';
export const FETCH_ALL_TRIBUTE_STATS_LIMITED = 'FETCH_ALL_TRIBUTE_STATS_LIMITED';
// (10) Global Event Management
export const FETCH_GLOBAL_EVENT = 'FETCH_GLOBAL_EVENT';
export const FETCH_GLOBAL_EVENTS = 'FETCH_GLOBAL_EVENTS';